# Generated by Django 5.2.7 on 2025-10-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='udpated_at',
            new_name='updated_at',
        ),
    ]
